name: analytics_dbt
version: '1.0'
config-version: 2

profile: analytics_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  analytics_dbt:
    staging:
      +materialized: view