analytics_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1        # or “127.0.0.1”
      user: dbuser
      password: dbpass
      port: 5432
      dbname: analytics
      schema: staging
