version: 2

sources:
  - name: chicago_crimes
    tables:
      - name: raw_chicago_crimes

models:
  - name: stg_chicago_crimes
    description: "Cleaned Chicago crimes staging table"
    columns:
      - name: case_id
        tests:
          - not_null
          - unique